apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: chicago-traffic-ingest
  labels:
    name: chicago-traffic-ingest
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: chicago-traffic-ingest
        spec:
          containers:
          - name: chicago-traffic-ingest
            image: gcr.io/traffic-telemetry-proto/chicago-traffic-ingest:latest
            env:
            - name: PROJECT_ID
              value: traffic-telemetry-proto
            - name: PUBSUB_TOPIC
              value: projects/traffic-telemetry-proto/topics/chicago-traffic
          restartPolicy: OnFailure